server {
    listen 80;
    server_name your-ec2-public-dns-or-domain;

    location /static/ {
        alias /home/ubuntu/pagepulse_project/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/pagepulse_project/pagepulse.sock;
    }
}