# Generated by Django 5.0.7 on 2026-07-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('h1_count', models.PositiveIntegerField(blank=True, null=True)),
                ('images_total', models.PositiveIntegerField(blank=True, null=True)),
                ('images_missing_alt', models.PositiveIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
